### PR TITLE
Backport to 0.1: Shared must relinquish control to the executor if repolled

### PR DESCRIPTION
**Pull request by krallin**
This backports #2136 to Futures 0.1. There isn't much to add on top of
what's mentioned in #2136: the same bug exists in Futures 0.1, and it'll
fail in the same way when polled in recent versions of Tokio (#2418).

Backporting to 0.1 allows codebases that still have some Futures 0.1
code around to still use newer versions of Tokio.

### CODE REVIEW

**Comment by krallin** [comment]
Any thoughts? :)

**Comment by taiki-e** [comment]
#2122 hasn't been released yet, so it's nice to publish the next release of 0.1 after merging this.

(We need to decide how long we should maintain 0.1 branch, but this should be fine given that we have another backport already merged.)

**Comment by krallin** [comment]
Could we get this merged and released? Having futures 0.1 being broken on newer versions of Tokio makes upgrading Tokio more painful than it should be :(

**Comment by taiki-e** [comment]
Thanks, I'll prepare the next release.

**Comment by krallin** [comment]
Thanks a lot @taiki-e !

**Comment by krallin** [comment]
Hey @taiki-e , I'm sorry to be a bit of a bother here, but has this made it into a new release yet? Thanks :)

**Comment by taiki-e** [comment]
Published 0.1.30, sorry for the delay.

**Comment by krallin** [comment]
Thanks very much!

**Pull request merged**
