### PR TITLE
Added a `is_connected_to` to (`Unbounded`)`Sender`

### PR DESCRIPTION
**Pull request by LinkTed**
Hi,
I added a `is_receiver` function to the (`Unbounded`)`Sender` struct to check if a sender object belongs to this specific receiver object. The code is similar to `same_receiver` function.

### CODE REVIEW

**Comment by LinkTed** [comment]
Does someone know why Travis get this error?
```
error: failed to parse manifest at `/Users/travis/build/rust-lang/futures-rs/examples/functional/Cargo.toml`
```
I did not change anything in `Cargo.toml`.

**Comment by taiki-e** [comment]
That is cargo bug: rust-lang/cargo#8351

**Comment by LinkTed** [comment]
@taiki-e ohh thanks :)

**Comment by taiki-e** [comment]
Also, there is a PR that adds a similar method to oneshot (#2158), it seems to makes sense to use the same method name as that PR.

**Comment by LinkTed** [comment]
Done

**Review by taiki-e — APPROVED** [review]
Thanks!

**Pull request merged**
