### PR TITLE
Implement `FusedStream` for `FuturesOrdered`

### LINKED ISSUE #2192: Why is there no `FusedStream` implementation for `FuturesOrdered`?
While `FuturesUnordered` has a [`FusedStream` implementation](https://docs.rs/futures/0.3.5/futures/stream/struct.FuturesUnordered.html#impl-FusedStream), the `FuturesOrdered` type does not. Is there any reason for this missing implementation or is this just an oversight?

### PR DESCRIPTION
**Pull request by phil-opp**
This uses the same approach as the `FusedStream` implementation for `FuturesUnordered`.

Fixes #2192 

cc @taiki-e

### CODE REVIEW

**Comment by taiki-e** [comment]
`FuturesUnordered` implements `FusedStream` with the same logic that this PR introduces, and `is_terminated` field is `true` only when `in_progress_queue.poll_next_unpin()` returns `None`, so I think `self.in_progress_queue.is_terminated() && self.queued_outputs.is_empty()` is enough for this.

**Comment by phil-opp** [comment]
Thanks for the suggestion, I pushed a new commit with it.

**Review by taiki-e — APPROVED** [review]

**Comment by phil-opp** [comment]
The clippy failure in src/mpsc/mod.rs seems unrelated to this PR.

**Comment by taiki-e** [comment]
Yes, that will be fixed in #2203

**Comment by taiki-e** [comment]
Thanks!

**Pull request merged**
