### PR TITLE
full working example for oneshot

### PR DESCRIPTION
**Pull request by tworec**
A friend of mine was confused by the current example for oneshot channel.
I'm proposing more illustrative and *WORKING* version here ;)

Inspiration from: https://doc.rust-lang.org/std/sync/mpsc/fn.channel.html

### CODE REVIEW

**Comment by tworec** [comment]
notice that lines starting with
```
/// # 
```
are not visible on [docs.rs](https://docs.rs/futures/0.3.4/futures/channel/oneshot/fn.channel.html)

**Comment by cramertj** [comment]
Nice, this looks like a good improvement. Would you mind also moving this test over to use async/await like our other examples?

**Comment by tworec** [comment]
is this what you are asking for?

**Comment by cramertj** [comment]
Normally we hide the `block_on` in our examples, but this works fine, thanks!

**Pull request merged**
