### PR TITLE
Replace _priv field by tuple field

### PR DESCRIPTION
**Pull request by olegnn**

### CODE REVIEW

**Comment by seanmonstar** [comment]
Why make this change? These types are purposefully _not_ tuple structs to prevent people from innocently matching them as such (like `Err(TryRecvError(..))`.

**Comment by olegnn** [comment]
@seanmonstar `(())` works exactly the same way as `{ _priv: () }` (defines one private field to prevent pattern matching etc) except that it's more convenient to use.

**Comment by taiki-e** [comment]
`_priv` field is not actually used and more descriptive than the unnamed field, so I prefer not to change this.

**Comment by cramertj** [comment]
I agree with other comments. I think the old syntax was clearer about the intent of the field. Thanks for helping look for opportunities to clean up the codebase, though!

**Pull request closed without merging**
