### PR TITLE
Add strong/weak pointer counts to Shared

### LINKED ISSUE #2330: Expose strong/weak count for Shared
It'd be nice to have some of way to count the number of pointers to the `Shared` future.

### PR DESCRIPTION
**Pull request by hlb8122**
Closes #2330

### CODE REVIEW

**Comment by hlb8122** [comment]
CI failing on `1.37.0` and `1.39.0` due `use of unstable library feature 'weak_counts'`. Any advice on how I should proceed?

**Comment by taiki-e** [comment]
> CI failing on `1.37.0` and `1.39.0` due `use of unstable library feature 'weak_counts'`. Any advice on how I should proceed?

I would prefer to add these methods only to `Shared` for now. (but, if someone *really* needs `WeakShared::*count`, I'm okay with adding it using a build script.)

**Comment by hlb8122** [comment]
I personally have no use for `WeakShared::*_count`, I added them to anticipate a request for them. Removing them for now.

**Review by taiki-e — APPROVED** [review]
Thanks!

**Pull request merged**
