### PR TITLE
Prepare 0.1.30

### PR DESCRIPTION
**Pull request by taiki-e**
This includes a bug fix (#1864) and compatibility fixes with tokio 0.2 (#2122, #2154).

r? @cramertj

### CODE REVIEW

**Comment by cramertj** [comment]
LGTM! I sent you an owner invite for the crate as well if you want to publish it. Otherwise, lmk and I can do it. Thanks!

**Comment by taiki-e** [comment]
@cramertj Thanks! I'll publish a new version:)

**Comment by taiki-e** [comment]
@cramertj Would you give me a publish permission of [futures01](https://crates.io/crates/futures01)? (and if possible, also the sub crates included in 0.3 -- I'll open a PR later, but many changes have been merged into master since the previous version was released, so I also would like to make a new release of 0.3.)

**Comment by taiki-e** [comment]
Published 0.1.30 and opened #2226 for the next release of 0.3.

**Comment by cramertj** [comment]
@taiki-e Sent invites for `futures01` and the subcrates. Thanks so much!

**Comment by taiki-e** [comment]
Thanks, I published futures01 0.1.30. I'll publish the next release of futures 0.3 and sub crates after merge #2226.

**Pull request merged**
