### PR TITLE
extend example for join!/try_join!

### LINKED ISSUE #2120: Expand futures::join example to show that it is variadic
Currently the example only shows a 2-tuple being joined, should make it more obvious that the macro is variadic.

### PR DESCRIPTION
**Pull request by JOE1994**
Hello :crab: , this PR makes the following change.
* Update examples for `join!`/`try_join!` to make explicit that these macros are variadic.

closes #2120 

Thank you for reviewing this PR :+1:

### CODE REVIEW

**Comment by JOE1994** [comment]
The initial commit failed in CI due to an issue external to this PR

**Review by taiki-e — COMMENTED** [review]
I think it is easier to read if the definitions of variable a,b and variable c,d,e are separated.

Also, CI failure will be fixed in #2203

**Comment by taiki-e** [comment]
Also, it may be good to add a comment explaining "variadic" after the comment "`join!`/`try_join!` is variadic". 
e.g., "`join!` is variadic, so you can pass any number of futures."

**Comment by JOE1994** [comment]
> Also, it may be good to add a comment explaining "variadic" after the comment "`join!`/`try_join!` is variadic".
> e.g., "`join!` is variadic, so you can pass any number of futures."

Thank you for your feedback! I made commits to apply the suggested changes :smiley_cat:

**Review by taiki-e — APPROVED** [review]

**Comment by taiki-e** [comment]
Thanks!

**Pull request merged**
